function configs = defineCompleteAblationConfigurations()
    % Simplified ablation study with 6 key configurations
    configs = {};

    % 1. BASELINE: Pure PSO (no neural network)
    configs{end+1} = struct(...
        'name', 'Baseline_Pure_PSO', ...
        'useNeuralGuidance', false, ...
        'networkArchitecture', 'none', ...
        'featureSet', 'none', ...
        'trainingStrategy', 'none', ...
        'adaptiveInfluence', false, ...
        'maxGamma', 0.0);

    % 2. FULL SYSTEM: Everything enabled (14 features, adaptive gamma)
    configs{end+1} = struct(...
        'name', 'Full_System', ...
        'useNeuralGuidance', true, ...
        'networkArchitecture', 'deep', ...
        'featureSet', 'full', ...  % All 14 features (F1-F14: includes unified convergence-stagnation index)
        'trainingStrategy', 'online', ...
        'adaptiveInfluence', true, ...
        'maxGamma', 1.0);

    % 3. WITHOUT STAGNATION FEATURES: Old system (12 features only)
    configs{end+1} = struct(...
        'name', 'Without_Stagnation_Features', ...
        'useNeuralGuidance', true, ...
        'networkArchitecture', 'deep', ...
        'featureSet', 'without_stagnation', ...  % F1-F10 + F13-F14 only (excludes F11: convergence-stagnation, F12: spatial consistency)
        'trainingStrategy', 'online', ...
        'adaptiveInfluence', true, ...
        'maxGamma', 1.0);

    % 4. NO TRAINING: Random untrained network
    configs{end+1} = struct(...
        'name', 'Random_NN_No_Training', ...
        'useNeuralGuidance', true, ...
        'networkArchitecture', 'deep', ...
        'featureSet', 'full', ...
        'trainingStrategy', 'none', ...  % No learning
        'adaptiveInfluence', true, ...
        'maxGamma', 1.0);

    % 5. FIXED GAMMA: No adaptive influence (constant 50/50)
    configs{end+1} = struct(...
        'name', 'Fixed_Gamma_0_5', ...
        'useNeuralGuidance', true, ...
        'networkArchitecture', 'deep', ...
        'featureSet', 'full', ...
        'trainingStrategy', 'online', ...
        'adaptiveInfluence', false, ...
        'maxGamma', 0.5);

    % 6. SHALLOW NETWORK: Simpler architecture
    configs{end+1} = struct(...
        'name', 'Shallow_Network', ...
        'useNeuralGuidance', true, ...
        'networkArchitecture', 'shallow', ...
        'featureSet', 'full', ...
        'trainingStrategy', 'online', ...
        'adaptiveInfluence', true, ...
        'maxGamma', 1.0);
end

